### ISSUE TITLE
RISC-V ISA string(described in Chapter 28 of the RISC-V specification(unpriv))

### ISSUE THREAD

**Issue by jenish4** [pawks/lfx-mentorship#1]
Chapter 28 is History and Acknowledgements. I think you meant Chapter 27 - ISA Extension Naming Conventions. Please confirm. Thank you.

**Comment by pawks** [comment]
Yes. Chapter 27 in the version dated: 20191213(available on the specifications page of RISCV website) and Chapter 28 in the latest version of the repo.

**Comment by jenish4** [comment]
Okay, thanks. I was referring to the version you have attached with task 1.
