### ISSUE TITLE
Task 1 Example

### ISSUE THREAD

**Issue by jenish4** [pawks/lfx-mentorship#2]
> "Example: for RV32IM, two relevant coverpoints are to check whether the bit at index 12 of misa is 0 and 1(misa && 0x1000 == 0x1000)."

In this, if **RV32IM** is the input string, the output that we should get is:
```
misa && 0x100 == 0x100
misa && 0x1000 == 0x1000
```

One coverpoint each for **I** and **M**.
Right? Please correct me if I am missing something.

Could you also elaborate on 

> "Briefly describe the events (i.e list out the possible exceptions and why) in the test which will occur while testing one such coverpoint."

Thank you.

**Comment by pawks** [comment]
> > "Example: for RV32IM, two relevant coverpoints are to check whether the bit at index 12 of misa is 0 and 1(misa && 0x1000 == 0x1000)."
> 
> In this, if **RV32IM** is the input string, the output that we should get is:
> 
> ```
> misa && 0x100 == 0x100
> misa && 0x1000 == 0x1000
> ```
If you are testing for both I and M, yes. Those are 2 of the 3 possible coverpoints. The example is given only for one of the coverpoints. 
> 
> One coverpoint each for **I** and **M**. Right? Please correct me if I am missing something.
> 
> Could you also elaborate on
> 
> > "Briefly describe the events (i.e list out the possible exceptions and why) in the test which will occur while testing one such coverpoint."
> 
Based on the behavior of `misa`, you will need to describe the exceptions which can occur when you try to test a coverpoint. It is not enough to test whether the update the csr has gone through, as the values in the csrs control the execution behavior of the program. Hence, you will also have to describe the scenario which lets us validate the behavior corresponding to the coverpoint.
> Thank you.

**Comment by jenish4** [comment]
> > > "Example: for RV32IM, two relevant coverpoints are to check whether the bit at index 12 of misa is 0 and 1(misa && 0x1000 == 0x1000)."
> > 
> > 
> > In this, if **RV32IM** is the input string, the output that we should get is:
> > ```
> > misa && 0x100 == 0x100
> > misa && 0x1000 == 0x1000
> > ```
> 
> If you are testing for both I and M, yes. Those are 2 of the 3 possible coverpoints. The example is given only for one of the coverpoints.

Is the third coverpoint also for extension field only or other fields as well?

> 
> > One coverpoint each for **I** and **M**. Right? Please correct me if I am missing something.
> > Could you also elaborate on
> > > "Briefly describe the events (i.e list out the possible exceptions and why) in the test which will occur while testing one such coverpoint."
> 
> Based on the behavior of `misa`, you will need to describe the exceptions which can occur when you try to test a coverpoint. It is not enough to test whether the update the csr has gone through, as the values in the csrs control the execution behavior of the program. Hence, you will also have to describe the scenario which lets us validate the behavior corresponding to the coverpoint.
> 

Does this have to be described as a write-up or in the form of some code?

> > Thank you.
