### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by jenish4** [pawks/lfx-mentorship#3]
Please explain what we have to do in this task. We have to write a RISC-V assembly code? But how will it include the coverpoints since we are simply giving the string like "RV32IM"?

Thank You.

**Comment by pawks** [comment]
Each of the coverpoints can be converted into a sequence of assembly instructions which manipulate the states such that the coverpoint can be satisfied. You have to write an assembly program which manipulates the states for one of the coverpoints.

**Comment by jenish4** [comment]
Thank you. I have updated my [submission ](https://github.com/jenish4/LFX-Mentorship/tree/main) based on my understanding.
